### ISSUE TITLE
点击 checkbox 时,不会立刻切换选中状态

### ISSUE THREAD

**Issue by Aaron-Bird** [x-extends/vxe-table-plugin-virtual-tree#11]
**（必填）请填写问题描述或截图：**

如果 tableData 缺少使用 checkbox-config.checkField 参数定义的键名, 点击 checkbox 时不会立刻切换选中状态

![1](https://user-images.githubusercontent.com/25508292/92359684-42305c80-f11e-11ea-9c93-f4cf718069f1.gif)  
  
**（必填）请填在线链接：**

https://jsrun.net/9nLKp/edit

**（必填）请填写期望的结果：**

点击 checkbox 后立刻切换选中状态

**（必填）请填写以下信息：**

- OS: Windows
- Browser: chrome
- vue: 2.6.11
- vxe-table: 2.9.20-beta.3
- vxe-table-plugin-virtual-tree: 0.4.1

**Comment by xuliangzhan** [comment]
这个你应该去看 vue 的文档，响应式属性必须要先定义
https://cn.vuejs.org/v2/guide/reactivity.html#%E5%A3%B0%E6%98%8E%E5%93%8D%E5%BA%94%E5%BC%8F-property

**Comment by Aaron-Bird** [comment]
> 这个你应该去看 vue 的文档，响应式属性必须要先定义
> https://cn.vuejs.org/v2/guide/reactivity.html#%E5%A3%B0%E6%98%8E%E5%93%8D%E5%BA%94%E5%BC%8F-property

确实需要先定义.但数据量大的时候,每次从后台拉数据都要跑一遍递归,给所有对象加上个 checked .
可以在内部判断一下,不存在checked 的时候就添加一个 checked 属性吗?
