### ISSUE TITLE
npm 源安装后报错:  Cannot find module vxe-table-plugin-virtual-tree

### ISSUE THREAD

**Issue by Aaron-Bird** [x-extends/vxe-table-plugin-virtual-tree#14]
**（必填）请填写问题描述或截图：**

dist 文件夹里没有 package.json 中 main 参数配置的 js 文件

```
 "main": "dist/vxe-table-plugin-virtual-tree.common.js",
```

**（必填）请填在线链接：**

https://jsrun.net/

**（必填）请填写期望的结果：**

将 package.json 的 main 参数指向正确的路径

**（必填）请填写以下信息：**

- OS: Windows
- Browser: chrome
- vue: 2.6.11
- vxe-table: 2.9.20-beta.3
- vxe-table-plugin-virtual-tree: 0.5.0

**Comment by xuliangzhan** [comment]
更新最新试试

**Comment by Aaron-Bird** [comment]
该bug已于0.5.4版本修复

**Comment by 2663272622** [comment]
垃圾东西
