### ISSUE TITLE
快速拉动滚动条时,未显示正确的行, 且右侧固定列 的 marginTop 计算错误

### ISSUE THREAD

**Issue by Aaron-Bird** [x-extends/vxe-table-plugin-virtual-tree#17]
**（必填）请填写问题描述或截图：**
![96000224-42ccb900-0e69-11eb-8015-325fc938ef07](https://user-images.githubusercontent.com/25508292/96002123-5aa53c80-0e6b-11eb-8701-88a9eae1feeb.png)

复现过程:
快速拉动右侧滚动条, 有几率出现右侧固定列不显示的情况.且非滚动列也没有正确显示相应的行.

![1](https://user-images.githubusercontent.com/25508292/96001158-4d3b8280-0e6a-11eb-8b2f-8dec73f1f10d.gif)

**（必填）请填在线链接：**

10/15日补充:
原来的demo貌似不太好复现, 新增一个.
貌似当右侧固定列使用 slots,且 slot 内使用了较复杂的 vue 组件时(右侧的固定列 常被用于放置大量的操作按钮 ),更容易复现这个问题.   

https://jsrun.net/fz6Kp/edit

---
原来的demo

https://jsrun.net/Wf6Kp/edit

**（必填）请填写期望的结果：**
1 拉动滚动条后正确的计算固定列的 marginTop 值
2 拉动滚动条后显示正确的行

**（必填）请填写以下信息：**

- OS: windows
- Browser: 2.9.25
- vue: 2.6.12
- vxe-table: 0.5.4

**Comment by Aaron-Bird** [comment]
临时解决办法
https://github.com/x-extends/vxe-table/issues/1042#issuecomment-708936789

**Comment by Aaron-Bird** [comment]
临时的解决办法:
1 跟踪 scroll 事件, 滚动结束后刷新 column.(2.9.18 以下版本需要此操作, 2.9.18 及以上版本应该不需要刷新column)
2 跟踪 scroll 事件, 滚动时不绘制右侧固定栏中的内容,直到滚动结束为止

**Comment by HenryLin0914** [comment]
請問最新版本有辦法解決嗎...

**Comment by xuliangzhan** [comment]
建议更新 2.10+ 试试，对虚拟滚动进行细微优化
https://jsrun.net/zMwKp/edit
